development:
  :proxy:
  :client_id: REPLACE_ME
  :client_secret: REPLACE_ME

test:
  :proxy:
  :client_id: REPLACE_ME
  :client_secret: REPLACE_ME

production:
  :proxy:
  :client_id: REPLACE_ME
  :client_secret: REPLACE_ME
