pirozhki_db_volume:
  image: ubuntu:14.04
  command: true
  volumes:
   - /var/lib/postgresql/data
   - /data

pirozhki_postgres:
  image: postgres:9.3
  environment:
    POSTGRES_USER: pirozhki
    POSTGRES_PASSWORD: mysecretpassword
  volumes_from:
    - pirozhki_db_volume

pirozhki_redis:
  image: redis:2.8
  command: redis-server --appendonly yes
  volumes_from:
    - pirozhki_db_volume

pirozhki_web:
  build: .
  command: puma -C config/sidekiq_web.rb
  environment:
    APP_ENV: production
  ports:
    - 9292:9292
  links:
    - pirozhki_redis:redis

pirozhki_workers:
  build: .
  command: sidekiq -r ./app.rb -C config/variables/sidekiq.yml
  environment:
    APP_ENV: production
  links:
    - pirozhki_postgres:postgres
    - pirozhki_redis:redis
