common: &default_settings
  instagram:
    proxy:
    request_delay: 0
    client_id: REPLACE_ME
    client_secret: REPLACE_ME
  web:
    username: admin
    password:
    session_secret:
  export:
    type: stdout
  logging:
    type: stdout
  newrelic:
    enabled: false
  rollbar:
    enabled: false

test:
  <<: *default_settings

development:
  <<: *default_settings

production:
  <<: *default_settings
  web:
    username: admin
    password: REPLACE_ME
    session_secret: REPLACE_ME
  export:
    type: logstash_tcp
    host: localhost
    port: 5229
  logging:
    type: file
  newrelic:
    enabled: true
  rollbar:
    enabled: true
    access_token: REPLACE_ME
